name: compile

on:
  push:
    branches:
      - community
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - configuration: Debug
            platform: Win32
          - configuration: Release
            platform: Win32
          - configuration: Debug
            platform: x64
          - configuration: Release
            platform: x64
    steps:
      - uses: actions/checkout@v6
      - name: install mfc atl
        shell: pwsh
        run: |
          $vsInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"
          $installPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          & $vsInstaller modify --installPath $installPath --add Microsoft.VisualStudio.Component.VC.ATLMFC --passive --norestart
      - uses: microsoft/setup-msbuild@v3
      - name: setup dependencies
        shell: pwsh
        run: |
          choco install -y 7zip nasm strawberryperl
          $ErrorActionPreference = 'Stop'
          7z x -y Src/winampAll/libvpx_v1.8.2_msvc16.7z -oSrc
          7z x -y Src/winampAll/libmpg123.7z -oSrc
          7z x -y BuildTools/lib/microsoft_directx_sdk_2010.7z -oSrc/external_dependencies
          7z x -y BuildTools/lib/intel_ipp_6.1.1.035.7z -oSrc/external_dependencies
      - name: build
        shell: pwsh
        run: msbuild winampAll_2019.sln /m /p:Configuration=${{ matrix.configuration }} /p:Platform="${{ matrix.platform }}"
